### ISSUE TITLE
not selecting the input specified in selected

### ISSUE THREAD

**Issue by rachel-forty** [moj-analytical-services/shinyGovstyle#26]
https://github.com/moj-analytical-services/shinyGovstyle/blob/a7d58bb2cf45a945cf8ea0f1909c545d15b1b9c7/R/radio_button_input.R#L74

Afraid I'm not sure how to test this one, when vaguely trying to run the lines of the function, 'selected <- as.character(selected)' gave 'Error in args(obj) : could not find function "complete"' where selected was equal to "complete" but could be that I was not doing something valid!

**Comment by rosswyatt** [comment]
This happens as I wasn't sure about the default behaviour that sets the default to the 1st option if selected = NULL.  I have reworked the it radio-default-fix branch, but this is less robust.  You will now get an error if there selected variable doesn't exist.

**Comment by rosswyatt** [comment]
Pulled this into master as it doesn't seem to create an issue in testing
