### ISSUE TITLE
Use of `norem`

### ISSUE THREAD

**Issue by admivsn** [moj-analytical-services/shinyGovstyle#55]
Hi,

This is amazing work and a really cool package! I was wondering what the use of `norem` is in the css file?

I might be wrong but is it just because `rem` definitions would mess with shiny bootstrap? So changing it to `norem` invalidates that line of css?

The reason I ask is I am looking from a similar perspective using the NHS frontend toolkit (with limited css knowledge)!.. the compiled files don’t work out of the box (for font sizes) but I have found removing the `rem` lines helps (a long process and I realise changing to `norem` would be much faster). Maybe this is a similar issue that you faced so just intrigued as to the best solution. 

Thanks in advance, Adam

**Comment by rosswyatt** [comment]
Yeah the norem just invalidates the line.  I am being lazy TBH to get rid of the problem.  I am planning on writing something that changes the rem to a px value instead rather than just invalidates them.

**Comment by admivsn** [comment]
Thanks for the clarification! I will close this now
