### ISSUE TITLE
Update to GDS Frontend v5+

### ISSUE THREAD

**Issue by cjrace** [moj-analytical-services/shinyGovstyle#60]
The [GDS frontend is currently at v5.3.0](https://github.com/alphagov/govuk-frontend/releases/tag/v5.3.0), this package is currently on v4.something.

v5 was a big step change for a chunk of things. We should update the components in this package to match - expecting it will be a fairly big job to go through and check them all individually, so worth chunking up once the initial update of the CSS etc is on a branch.

**Comment by sarahmwong** [comment]
Bits I've spotted that we should update - please add if I've missed anything!

- [ ] App title header text looks to small compared to department name
- [ ] Radio buttons - centralise text when inline = TRUE
- [ ] File upload - looks like default shiny styling, needs to point to right css element?
- [ ] Back link - needs styling - may just need to point to correct css element
- [ ] Inactive tag - need to add to run_example to test
- [ ] Warning text - currently prints out "Warning" after the inputted text in the function - think this is an error
- [ ] Cookie banner not working - this is a separate issue #67

**Comment by cjrace** [comment]
Add a few extra bits I think we should check to the list above. Might be worth adding extra tabs to the example dashboard to test them with more easily?

For the cookie banner not working I think we should potentially just leave that for the separate issue to pick up?

And then final mop up steps

- [ ] Document process for updating CSS
- [ ] Update css_changes.md file
- [ ] Update version number
- [ ] New release to CRAN?

**Comment by sarahmwong** [comment]
Thanks Cam! I'll message the assignees in our teams and randomly assign bits to check/see if they're happy. Agreed cookies one can be removed and treated as separate issue. Would we want to merge to dev first along with the other changes in the issue log so we only need to do one CRAN release? Or if you think these changes are more urgently needed happy to see what we need to do to release it sooner 😄

**Comment by cjrace** [comment]
Let's merge to dev first and then see where we're at?

I think I might have just resolved two of the ones I added already as I got a bit carried away and started testing things out straight away! The beta banner and back link ones I'll make a quick PR pointing at to the update-to-gds-v5.4 branch shortly for you / someone else to take a look at 😄

**Comment by rmbielby** [comment]
Here's the before and afters for govTable and govTabs. As far as I can see govTable looks fine, govTabs has the border line going all the way round instead of leaving a gap where the tab label is. If anyone else wants to play spot the difference and sees anything else that's not formatted as before, let me know!

![govTabs-govTable-original](https://github.com/user-attachments/assets/89f5c462-53e8-429a-ad94-a1dd94989f45)

![govTabs-govTable-gds5 4](https://github.com/user-attachments/assets/c2918d77-b169-4ed4-bd94-f6dc04bc31e7)

**Comment by sarahmwong** [comment]
Cheers Rich! Just thinking - please could you add them in to the run_example()? That will save people a job of running it separately to check in future too 😄

**Comment by rmbielby** [comment]
Yep, done that as part of the above. Will add it to the branch as part of the update. Also, looks like it's a bit worse for tabs than it first looked. I tried clearing out my browser data just to make sure there was no legacy css in memory that was interfering and it then produced this:
![image](https://github.com/user-attachments/assets/1a0a022b-e0c9-4e8f-8ddb-cb42d6d9a591)

**Comment by rmbielby** [comment]
Ok, got all that fixed now I think, making a PR.
