### ISSUE TITLE
Add example valueboxes

### ISSUE THREAD

**Issue by cjrace** [moj-analytical-services/shinyGovstyle#68]
Not in the GDS frontend, though a standard function for accessible value boxes in R Shiny would be a neat addition and save some pain / coding across other dashboards.

Example kind of thing:

![image](https://github.com/moj-analytical-services/shinyGovstyle/assets/52536248/12a86fc9-19b9-402e-8966-c87d2f8f5190)

**Comment by TomDougall** [comment]
Think this issue can be closed now.
