### ISSUE TITLE
ID generation for accordion fails when there are 10 or more sections

### ISSUE THREAD

**Issue by fingertipsy** [moj-analytical-services/shinyGovstyle#92]
The accordion "show" buttons are not functioning correctly for sections with indices greater than 9.
It seems the IDs for sections with indices greater than 9 are causing conflicts in the HTML. The result is that the "show content" button for section 11 open the content for section 1, 12 opens 2 and so forth.

**Comment by jenisayshi** [comment]
think this is caused by this line in the accordian.js code only picking up the last digit of the heading :)
  
 // get z value from name (Map argument)
  var level = str.substring(str.length - 1);
